2025-04-07 06:08:09,363 [DEBUG] Using selector: EpollSelector
2025-04-07 06:08:18,799 [DEBUG] Submitted data: full_name='asdasd', url='asdasd', customer_name='mufiksoft123'
2025-04-07 06:08:18,904 [DEBUG] Checking if customer 'mufiksoft123' exists in DB...
2025-04-07 06:08:18,906 [DEBUG] Result from DB: (0,)
2025-04-07 06:08:18,907 [DEBUG] Inserting customer 'mufiksoft123' into DB...
2025-04-07 06:08:18,940 [ERROR] Exception occurred:
Traceback (most recent call last):
  File "/mnt/d/projects/crmsis-1/config/composes/new_client_app/venv/lib/python3.10/site-packages/mysql/connector/connection_cext.py", line 365, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Access denied for user 'XQWhWzoQr0LxqlOnuGQV'@'172.18.0.1' (using password: YES)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/d/projects/crmsis-1/config/composes/new_client_app/commands/add.py", line 88, in on_button_pressed
    root_conn = self.connect_db("SB_CLIENTS_BACK_MYSQL_ROOT_PASSWORD", "SB_CLIENTS_BACK_MYSQL_ROOT_PASSWORD", "SB_CLIENTS_BACK_MYSQL_PORT")
  File "/mnt/d/projects/crmsis-1/config/composes/new_client_app/commands/add.py", line 37, in connect_db
    return mysql.connector.connect(
  File "/mnt/d/projects/crmsis-1/config/composes/new_client_app/venv/lib/python3.10/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/mnt/d/projects/crmsis-1/config/composes/new_client_app/venv/lib/python3.10/site-packages/mysql/connector/connection_cext.py", line 153, in __init__
    self.connect(**kwargs)
  File "/mnt/d/projects/crmsis-1/config/composes/new_client_app/venv/lib/python3.10/site-packages/mysql/connector/abstracts.py", line 1529, in connect
    self._open_connection()
  File "/mnt/d/projects/crmsis-1/config/composes/new_client_app/venv/lib/python3.10/site-packages/mysql/connector/connection_cext.py", line 370, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.ProgrammingError: 1045 (28000): Access denied for user 'XQWhWzoQr0LxqlOnuGQV'@'172.18.0.1' (using password: YES)
2025-04-07 06:13:22,813 [DEBUG] Using selector: EpollSelector
2025-04-07 06:13:26,957 [DEBUG] Submitted data: full_name='asdas', url='asdasd', customer_name='asdasd'
2025-04-07 06:13:27,093 [DEBUG] Checking if customer 'asdasd' exists in DB...
2025-04-07 06:13:27,095 [DEBUG] Result from DB: (0,)
2025-04-07 06:13:27,095 [DEBUG] Inserting customer 'asdasd' into DB...
2025-04-07 06:13:27,185 [INFO] Created database SB_PD_ASDASD and granted access to sb_usr
2025-04-07 06:13:27,199 [INFO] Created database SB_WH_ASDASD and granted access to sb_usr
2025-04-07 06:13:27,201 [ERROR] Exception occurred:
Traceback (most recent call last):
  File "/mnt/d/projects/crmsis-1/config/composes/new_client_app/commands/add.py", line 112, in on_button_pressed
    generate_compose_file(
  File "/mnt/d/projects/crmsis-1/config/composes/new_client_app/commands/helpers.py", line 21, in generate_compose_file
    with open(template_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '../composes/docker-compose-sb-b-app-template.yml'
2025-04-07 06:14:40,974 [DEBUG] Using selector: EpollSelector
2025-04-07 06:14:44,416 [DEBUG] Submitted data: full_name='asdasd', url='asdas', customer_name='asasd'
2025-04-07 06:14:44,546 [DEBUG] Checking if customer 'asasd' exists in DB...
2025-04-07 06:14:44,548 [DEBUG] Result from DB: (0,)
2025-04-07 06:14:44,548 [DEBUG] Inserting customer 'asasd' into DB...
2025-04-07 06:14:44,601 [INFO] Created database SB_PD_ASASD and granted access to sb_usr
2025-04-07 06:14:44,613 [INFO] Created database SB_WH_ASASD and granted access to sb_usr
2025-04-07 06:14:44,619 [INFO] Generated docker-compose file: docker-compose-sb-b-app-asasd.yml
2025-04-07 06:14:44,623 [INFO] Generated docker-compose file: docker-compose-sb-b-app-wh-asasd.yml
2025-04-07 06:14:44,624 [WARNING] nginx config not found: ../config/config/nginx/nginx.conf
2025-04-07 06:18:02,597 [DEBUG] Using selector: EpollSelector
2025-04-07 06:18:06,040 [DEBUG] Submitted data: full_name='fghfg', url='fghfgh', customer_name='fghfg'
2025-04-07 06:18:06,174 [DEBUG] Checking if customer 'fghfg' exists in DB...
2025-04-07 06:18:06,175 [DEBUG] Result from DB: (0,)
2025-04-07 06:18:06,176 [DEBUG] Inserting customer 'fghfg' into DB...
2025-04-07 06:18:06,260 [INFO] Created database SB_PD_FGHFG and granted access to sb_usr
2025-04-07 06:18:06,275 [INFO] Created database SB_WH_FGHFG and granted access to sb_usr
2025-04-07 06:18:06,281 [INFO] Generated docker-compose file: ../../composes/docker-compose-sb-b-app-fghfg.yml
2025-04-07 06:18:06,286 [INFO] Generated docker-compose file: ../../docker-compose-sb-b-app-wh-fghfg.yml
2025-04-07 06:18:06,286 [WARNING] nginx config not found: ../../config/config/nginx/nginx.conf
2025-04-07 06:19:17,440 [DEBUG] Using selector: EpollSelector
2025-04-07 06:19:21,219 [DEBUG] Submitted data: full_name='sadsa', url='asdas', customer_name='asdas'
2025-04-07 06:19:21,386 [DEBUG] Checking if customer 'asdas' exists in DB...
2025-04-07 06:19:21,387 [DEBUG] Result from DB: (0,)
2025-04-07 06:19:21,388 [DEBUG] Inserting customer 'asdas' into DB...
2025-04-07 06:19:21,443 [INFO] Created database SB_PD_ASDAS and granted access to sb_usr
2025-04-07 06:19:21,457 [INFO] Created database SB_WH_ASDAS and granted access to sb_usr
2025-04-07 06:19:21,463 [INFO] Generated docker-compose file: ../../composes/docker-compose-sb-b-app-asdas.yml
2025-04-07 06:19:21,468 [INFO] Generated docker-compose file: ../../composes/docker-compose-sb-b-app-wh-asdas.yml
2025-04-07 06:19:21,477 [INFO] Backup saved: ../../config/nginx/nginx.conf.bak
2025-04-07 06:19:21,483 [INFO] Nginx config updated at ../../config/nginx/nginx.conf
